version: "3"
services:
  mockoon:
    image: mockoon/cli:latest
    command: mockoon-cli start --data data
    container_name: myapi
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./data.json
        target: /data 
