version: "2.4"
services:
  mockServer:
    image: mockserver/mockserver:5.14.0
    container_name: mockserver-api
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/data.json
    volumes:
      - type: bind
        source: mockserver-config
        target: /config
