name: CI

on:
  push:
jobs:
  # イメージのビルド
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build mock Runner
        run: |
          docker-compose up -d
          # docker run -d --mount type=bind,source=${{ github.workspace }}/sampleAPI.json,target=/sampleAPI,readonly -p 3000:3000 mockoon/cli:latest -d sampleAPI -i 0 -p 3000
      - name: Check mock
        run: |
          ps -ef
          curl -vl http://127.0.0.1:3000/users
