name: CI

on:
  push:
jobs:
  # イメージのビルド
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: build mockoon Runner
        run: |
          docker-compose -f docker-compose-mockoon.yml up -d
          # docker run -d --mount type=bind,source=${{ github.workspace }}/sampleAPI.json,target=/sampleAPI,readonly -p 3000:3000 mockoon/cli:latest -d sampleAPI -i 0 -p 3000
      - name: Check mockoon
        run: |
          sleep 10
          docker ps
          curl -i http://127.0.0.1:3000/users
          docker-compose down

      - name: build mockserver Runner
        run: |
          docker-compose -f docker-compose-mockserver.yml up -d
      - name: Check mockserver
        run: |
          sleep 10
          docker ps
          curl -i http://127.0.0.1:1080/users
          docker-compose down
